# Generated by Django 4.2.6 on 2024-02-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Batallones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreB', models.CharField(max_length=100, verbose_name='Unidad')),
                ('ubicacionB', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('comandante', models.CharField(max_length=100, verbose_name='Comandante')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nombreB', models.CharField(max_length=100, verbose_name='Brigada')),
                ('ubicacionB', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('comandante', models.CharField(max_length=100, verbose_name='Comandante')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrigadaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado')),
                ('promocion', models.CharField(max_length=100, verbose_name='Promoción')),
                ('ano', models.CharField(max_length=100, verbose_name='Año')),
                ('unidad', models.CharField(max_length=100, verbose_name='Unidad')),
                ('datos', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('cedula', models.CharField(max_length=100, verbose_name='Cedula')),
                ('armaA', models.CharField(max_length=100, verbose_name='Arma de Asignada')),
                ('cargadores', models.CharField(max_length=100, verbose_name='Cargadores')),
                ('municiones', models.CharField(max_length=100, verbose_name='Municiones')),
                ('serialA', models.CharField(max_length=100, verbose_name='Serial del Arma')),
                ('serialAG', models.CharField(max_length=100, verbose_name='Serial de Asignacion')),
                ('fechaAG', models.CharField(max_length=100, verbose_name='Fecha de Asignacion')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreU', models.CharField(max_length=100, verbose_name='Unidad')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('img', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.brigadadigital')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.abastecimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Municiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoM', models.CharField(max_length=100, verbose_name='Carga Basica')),
                ('serialAG', models.CharField(max_length=100, verbose_name='Serial Asignado')),
                ('fechaAG', models.CharField(max_length=100, verbose_name='Fecha de Asignación')),
                ('cantidadM', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote N°')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tercero', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.batallones')),
            ],
        ),
        migrations.AddField(
            model_name='batallones',
            name='primero',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.brigada'),
        ),
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('tipoA', models.CharField(max_length=100, verbose_name='Tipo')),
                ('modeloA', models.CharField(max_length=100, verbose_name='Modelo')),
                ('calibreA', models.CharField(max_length=100, verbose_name='Calibre')),
                ('serialA', models.CharField(max_length=100, verbose_name='Serial')),
                ('serialAG', models.CharField(max_length=100, verbose_name='Serial del Asignación')),
                ('fechaAG', models.CharField(max_length=100, verbose_name='Fecha de Asignación')),
                ('opAM', models.CharField(max_length=100, verbose_name='Optimo')),
                ('cantidadA', models.CharField(max_length=100, verbose_name='Armas')),
                ('cantidadC', models.CharField(max_length=100, verbose_name='Cargadores')),
                ('armaS', models.CharField(max_length=100, verbose_name='Arma Segundaria')),
                ('calibreS', models.CharField(max_length=100, null=True, verbose_name='Calibre Segundario')),
                ('serialS', models.CharField(max_length=100, null=True, verbose_name='Serial Segundario')),
                ('cantidadS', models.CharField(max_length=100, null=True, verbose_name='Cantidad Segundario')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('segundo', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.batallones')),
            ],
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='productos',
            field=models.ManyToManyField(through='seajb.ProductoAbastecimiento', to='seajb.producto'),
        ),
    ]
