# Generated by Django 5.0.3 on 2024-04-16 14:47

import django.core.validators
import django.db.models.deletion
import seajb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Punto de Abastecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Batallones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreB', models.CharField(max_length=100, verbose_name='Unidad')),
                ('ubicacionB', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('comandante', models.CharField(max_length=100, verbose_name='Comandante')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('nombreB', models.CharField(max_length=100, verbose_name='Brigada')),
                ('ubicacionB', models.CharField(max_length=100, verbose_name='Ubicacion')),
                ('comandante', models.CharField(max_length=100, verbose_name='Comandante')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrigadaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cemanblin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(max_length=300, verbose_name='Nombre de la Unidad')),
                ('equipo', models.TextField(null=True, verbose_name='Equipo')),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('fechaE', models.DateField(verbose_name='Fecha de Entrega')),
                ('reparado', models.BooleanField(default=False)),
                ('seriales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personauna', models.CharField(max_length=300, verbose_name='Personas a Firmar')),
                ('personados', models.CharField(max_length=300)),
                ('personatres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cemansac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(max_length=300, verbose_name='Nombre de la Unidad')),
                ('equipo', models.TextField(null=True, verbose_name='Equipo')),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('fechaE', models.DateField(verbose_name='Fecha de Entrega')),
                ('reparado', models.BooleanField(default=False)),
                ('seriales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personauna', models.CharField(max_length=300, verbose_name='Personas a Firmar')),
                ('personados', models.CharField(max_length=300)),
                ('personatres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cemantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(max_length=300, verbose_name='Nombre de la Unidad')),
                ('equipo', models.TextField(null=True, verbose_name='Equipo')),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('fechaE', models.DateField(verbose_name='Fecha de Entrega')),
                ('reparado', models.BooleanField(default=False)),
                ('seriales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personauna', models.CharField(max_length=300, verbose_name='Personas a Firmar')),
                ('personados', models.CharField(max_length=300)),
                ('personatres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300, unique=True)),
                ('categoria', models.CharField(max_length=300, verbose_name='Categoria:')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado:')),
                ('promocion', models.TextField(null=True, verbose_name='Promoción:')),
                ('anio', models.IntegerField(validators=[seajb.models.validate_year], verbose_name='Año:')),
                ('unidad', models.TextField(null=True, verbose_name='Unidad:')),
                ('datos', models.CharField(max_length=300, verbose_name='Nombres y Apellidos:')),
                ('cedula', models.CharField(max_length=100, verbose_name='Cedula')),
                ('armaA', models.TextField(null=True, verbose_name='Arma de Asignada:')),
                ('cargadores', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cargadores:')),
                ('municiones', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carga Basica:')),
                ('serialA', models.CharField(max_length=100, verbose_name='Serial del Arma')),
                ('serialAG', models.CharField(max_length=100, verbose_name='Serial de Asignacion')),
                ('fechaAG', models.DateField(null=True, verbose_name='Fecha de Asignacion')),
                ('direccion', models.TextField(null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electronico')),
                ('img', models.ImageField(blank=True, default='/imagenes/nohay.jpg', null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Producto:')),
                ('serial', models.TextField(null=True, verbose_name='Serial')),
                ('modelo', models.CharField(max_length=500, verbose_name='Modelo')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=300, verbose_name='Categoria:')),
                ('tipoA', models.CharField(max_length=300, verbose_name='Tipo de Armas:')),
                ('modeloA', models.CharField(max_length=300, verbose_name='Modelo de la Armas:')),
                ('calibreA', models.CharField(max_length=300, verbose_name='Calibre de la Armas:')),
                ('serialA', models.CharField(max_length=8000, verbose_name='Serial de la Armas:')),
                ('serialAG', models.CharField(max_length=300, verbose_name='Serial del Asignación:')),
                ('fechaAG', models.DateField(verbose_name='Fecha de Asignación:')),
                ('opAM', models.CharField(max_length=300, verbose_name='Condiciones:')),
                ('cantidadA', models.IntegerField(verbose_name='Armas:')),
                ('cantidadC', models.IntegerField(verbose_name='Cargadores:')),
                ('ac', models.TextField(null=True, verbose_name='Accesorio:')),
                ('armaS', models.CharField(max_length=300, verbose_name='Arma Segundaria:')),
                ('calibreS', models.TextField(default=None, null=True, verbose_name='Tipo,Modelo,Calibre:')),
                ('serialS', models.TextField(blank=True, default=None, null=True, verbose_name='Serial Segundario:')),
                ('cantidadS', models.IntegerField(blank=True, default=None, null=True, verbose_name='Cantidad Segundario:')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('segundo', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.batallones')),
            ],
            options={
                'verbose_name_plural': 'Armas',
                'ordering': ['categoria'],
            },
        ),
        migrations.AddField(
            model_name='batallones',
            name='primero',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.brigada'),
        ),
        migrations.CreateModel(
            name='Municiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoM', models.CharField(max_length=100, verbose_name='Carga Basica')),
                ('serialAG', models.CharField(max_length=100, verbose_name='Serial Asignado')),
                ('fechaAG', models.DateField(verbose_name='Fecha de Asignación')),
                ('cantidadM', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote N°')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tercero', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.batallones')),
            ],
        ),
        migrations.CreateModel(
            name='ArmasDePersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armas', models.CharField(max_length=200, verbose_name='Armas Nuevas')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=200, verbose_name='Serial')),
                ('serialag', models.CharField(max_length=200, verbose_name='Serial de Asignación')),
                ('fechag', models.CharField(max_length=200, verbose_name='Fecha')),
                ('cargadores', models.CharField(max_length=200, verbose_name='Cargadores')),
                ('municiones', models.CharField(max_length=200, verbose_name='Munciones')),
                ('persona', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.personas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(max_length=200)),
                ('serial', models.TextField(null=True, verbose_name='serial')),
                ('fecha_salida', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('abastecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.abastecimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.producto')),
            ],
        ),
        migrations.AddField(
            model_name='abastecimiento',
            name='productos',
            field=models.ManyToManyField(through='seajb.ProductoAbastecimiento', to='seajb.producto'),
        ),
        migrations.CreateModel(
            name='UnidadDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreU', models.CharField(max_length=100, verbose_name='Unidad')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripcion')),
                ('img', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seajb.brigadadigital')),
            ],
        ),
    ]
