# Generated by Django 4.2.6 on 2024-03-04 17:07

import django.core.validators
from django.db import migrations, models
import seajb.models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personas',
            name='anio',
            field=models.IntegerField(validators=[seajb.models.validate_year], verbose_name='Año:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='armaA',
            field=models.CharField(max_length=100, verbose_name='Arma de Asignada:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='cargadores',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cargadores:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='datos',
            field=models.CharField(max_length=100, verbose_name='Nombres y Apellidos:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='fechaAG',
            field=models.DateField(verbose_name='Fecha de Asignacion'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='grado',
            field=models.CharField(max_length=100, verbose_name='Grado:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='municiones',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Carga Basica:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='promocion',
            field=models.CharField(max_length=100, verbose_name='Promoción:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='unidad',
            field=models.CharField(max_length=100, verbose_name='Unidad:'),
        ),
    ]
