# Generated by Django 5.0.3 on 2024-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fechaAG',
            field=models.DateField(null=True, verbose_name='Fecha de Asignacion'),
        ),
    ]
