# Generated by Django 5.0.3 on 2024-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
