# Generated by Django 4.2.6 on 2024-02-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmasDePersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armas', models.CharField(max_length=200, verbose_name='Armas Nuevas')),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=200, verbose_name='Serial')),
                ('serialag', models.CharField(max_length=200, verbose_name='Serial de Asignación')),
                ('fechag', models.CharField(max_length=200, verbose_name='Fecha')),
                ('cargadores', models.CharField(max_length=200, verbose_name='Cargadores')),
                ('municiones', models.CharField(max_length=200, verbose_name='Munciones')),
                ('persona', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='seajb.personas')),
            ],
        ),
    ]
