# Generated by Django 4.2.6 on 2024-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0002_producto_precio_alter_personas_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoabastecimiento',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
