# Generated by Django 5.0.3 on 2024-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemansac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(max_length=300, verbose_name='Nombre de la Unidad')),
                ('equipo', models.TextField(null=True, verbose_name='Equipo')),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('fechaE', models.DateField(verbose_name='Fecha de Entrega')),
                ('reparado', models.BooleanField(default=False)),
                ('seriales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personauna', models.CharField(max_length=300, verbose_name='Personas a Firmar')),
                ('personados', models.CharField(max_length=300)),
                ('personatres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cemantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200, unique=True)),
                ('unidad', models.CharField(max_length=300, verbose_name='Nombre de la Unidad')),
                ('equipo', models.TextField(null=True, verbose_name='Equipo')),
                ('fechaR', models.DateField(auto_now_add=True)),
                ('fechaE', models.DateField(verbose_name='Fecha de Entrega')),
                ('reparado', models.BooleanField(default=False)),
                ('seriales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personauna', models.CharField(max_length=300, verbose_name='Personas a Firmar')),
                ('personados', models.CharField(max_length=300)),
                ('personatres', models.CharField(max_length=300)),
            ],
        ),
    ]
