# Generated by Django 5.0.3 on 2024-03-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0002_alter_personas_fechaag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='img',
            field=models.ImageField(blank=True, default='imagenes/default.jpg', null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
