# Generated by Django 4.2.6 on 2024-03-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0003_alter_armas_calibres_alter_armas_serials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armas',
            options={'ordering': ['categoria'], 'verbose_name_plural': 'Armas'},
        ),
        migrations.AlterField(
            model_name='armas',
            name='armaS',
            field=models.BooleanField(default=False, verbose_name='Arma Segundaria'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibreS',
            field=models.CharField(blank=True, default='X', max_length=100, null=True, verbose_name='Calibre Segundario'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadA',
            field=models.IntegerField(verbose_name='Armas'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadC',
            field=models.IntegerField(verbose_name='Cargadores'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Segundario'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='fechaAG',
            field=models.DateField(verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialS',
            field=models.CharField(blank=True, default='X', max_length=100, null=True, verbose_name='Serial Segundario'),
        ),
    ]
