# Generated by Django 5.0.3 on 2024-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0003_alter_personas_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='armaA',
            field=models.TextField(null=True, verbose_name='Arma de Asignada:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='categoria',
            field=models.CharField(max_length=300, verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='code',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='datos',
            field=models.CharField(max_length=300, verbose_name='Nombres y Apellidos:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='promocion',
            field=models.TextField(null=True, verbose_name='Promoción:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='unidad',
            field=models.TextField(null=True, verbose_name='Unidad:'),
        ),
    ]
