# Generated by Django 4.2.6 on 2024-03-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0003_productoabastecimiento_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='productoabastecimiento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
