# Generated by Django 4.2.6 on 2024-03-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0004_alter_armas_options_alter_armas_armas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='armaS',
            field=models.BooleanField(default='No', verbose_name='Arma Segundaria'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibreS',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calibre Segundario'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialS',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Segundario'),
        ),
    ]
