# Generated by Django 5.0.3 on 2024-03-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0004_alter_personas_armaa_alter_personas_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='img',
            field=models.ImageField(blank=True, default='prueba.jpg', null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
