# Generated by Django 4.2.6 on 2024-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0005_alter_armas_armas_alter_armas_calibres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='armaS',
            field=models.CharField(max_length=100, verbose_name='Arma Segundaria'),
        ),
    ]
