# Generated by Django 5.0.3 on 2024-03-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0007_alter_personas_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='img',
            field=models.ImageField(blank=True, default='/imagenes/prueba.jpg', null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
