# Generated by Django 4.2.6 on 2024-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0007_alter_municiones_fechaag'),
    ]

    operations = [
        migrations.AddField(
            model_name='armas',
            name='ac',
            field=models.TextField(null=True, verbose_name='Accesorio'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibreA',
            field=models.CharField(max_length=100, verbose_name='Calibre de la Armas'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='modeloA',
            field=models.CharField(max_length=100, verbose_name='Modelo de la Armas'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='opAM',
            field=models.CharField(max_length=100, verbose_name='Condiciones'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialA',
            field=models.CharField(max_length=100, verbose_name='Serial de la Armas'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='tipoA',
            field=models.CharField(max_length=100, verbose_name='Tipo de Armas'),
        ),
    ]
