# Generated by Django 4.2.6 on 2024-03-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0008_armas_ac_alter_armas_calibrea_alter_armas_modeloa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='ac',
            field=models.TextField(null=True, verbose_name='Accesorio:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='armaS',
            field=models.CharField(max_length=300, verbose_name='Arma Segundaria:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibreA',
            field=models.CharField(max_length=300, verbose_name='Calibre de la Armas:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibreS',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Calibre Segundario:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadA',
            field=models.IntegerField(verbose_name='Armas:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadC',
            field=models.IntegerField(verbose_name='Cargadores:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadS',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Segundario:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='categoria',
            field=models.CharField(max_length=300, verbose_name='Categoria:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='fechaAG',
            field=models.DateField(verbose_name='Fecha de Asignación:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='modeloA',
            field=models.CharField(max_length=300, verbose_name='Modelo de la Armas:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='opAM',
            field=models.CharField(max_length=300, verbose_name='Condiciones:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialA',
            field=models.CharField(max_length=300, verbose_name='Serial de la Armas:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialAG',
            field=models.CharField(max_length=300, verbose_name='Serial del Asignación:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialS',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Serial Segundario:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='tipoA',
            field=models.CharField(max_length=300, verbose_name='Tipo de Armas:'),
        ),
    ]
