# Generated by Django 4.2.6 on 2024-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0009_alter_armas_ac_alter_armas_armas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='serialA',
            field=models.CharField(max_length=8000, verbose_name='Serial de la Armas:'),
        ),
    ]
