# Generated by Django 4.2.6 on 2024-03-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0010_alter_armas_seriala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='calibreS',
            field=models.CharField(max_length=300, null=True, verbose_name='Calibre Segundario:'),
        ),
    ]
