# Generated by Django 4.2.6 on 2024-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0012_alter_armas_calibres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='serialS',
            field=models.TextField(blank=True, null=True, verbose_name='Serial Segundario:'),
        ),
    ]
