# Generated by Django 4.2.6 on 2024-03-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seajb', '0013_alter_armas_serials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armas',
            name='calibreS',
            field=models.TextField(default=None, null=True, verbose_name='Tipo,Modelo,Calibre:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='cantidadS',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Cantidad Segundario:'),
        ),
        migrations.AlterField(
            model_name='armas',
            name='serialS',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Serial Segundario:'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
